#	SELECT * FROM REVIEWS;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE REVIEWS;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE BOARD(
	BD_NO INT AUTO_INCREMENT PRIMARY KEY,
	BD_TITLE VARCHAR(100) NOT NULL,
	BD_CONTENT VARCHAR(500) NOT NULL,
	BD_REGDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	BD_HIT INT NOT NULL,
	BD_FILENAME VARCHAR(300),
	BD_M_NO INT NOT NULL,
);
SELECT * FROM BOARD;
