#	SELECT * FROM REVIEWS;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE BOARD;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE BOARD(
	BD_NO INT AUTO_INCREMENT PRIMARY KEY,
	BD_TITLE VARCHAR(100) NOT NULL,
	BD_CONTENT VARCHAR(500) NOT NULL,
	BD_REGDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	BD_HIT INT NOT NULL,
	FILENAME VARCHAR(300),
	BD_M_NO VARCHAR(50) NOT NULL
);
SELECT * FROM BOARD;

INSERT INTO BOARD(BD_M_NO, BD_TITLE, BD_CONTENT, FILENAME, BD_REGDATE, BD_HIT) VALUES (2, DF, WW, "", DSF, NOW(), 0);