CREATE TABLE MEMBERS(
	M_NO INT AUTO_INCREMENT PRIMARY KEY,
	M_ID VARCHAR(50) NOT NULL UNIQUE,
	M_PW VARCHAR(64) NOT NULL,
	M_NAME VARCHAR(50) NOT NULL,
	M_ADDR1 VARCHAR(20),
	M_ADDR2 VARCHAR(100),
	M_ADDR3 VARCHAR(100),
	M_PHONE VARCHAR(20) NOT NULL,
	M_EMAIL VARCHAR(100) NOT NULL UNIQUE,
	M_GRADE VARCHAR(20) DEFAULT '일반등급',
	M_REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);